name: komodo-core

services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.107.0-ferretdb-2.7.0
    labels:
      komodo.skip:
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KOMODO_DB_USERNAME:-komodo}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${KOMODO_DB_USERNAME}
      POSTGRES_PASSWORD: ${KOMODO_DB_PASSWORD}
      POSTGRES_DB: postgres

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.7.0
    labels:
      komodo.skip:
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ferretdb-state:/state
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://${KOMODO_DB_USERNAME}:${KOMODO_DB_PASSWORD}@postgres:5432/postgres

  core:
    image: ghcr.io/moghtech/komodo-core:1.19.5
    labels:
      komodo.skip:
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    network_mode: host
    depends_on:
      ferretdb:
        condition: service_healthy
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: 127.0.0.1:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
      KOMODO_HOST: https://komodo.sharmamohit.com
      KOMODO_TITLE: Komodo
      KOMODO_LOCAL_AUTH: "true"
      KOMODO_DISABLE_USER_REGISTRATION: "true"
      KOMODO_ENABLE_NEW_USERS: "false"
      KOMODO_MONITORING_INTERVAL: "15-sec"
      KOMODO_RESOURCE_POLL_INTERVAL: "1-hr"
      TZ: America/Vancouver
    volumes:
      - /etc/komodo/backups:/backups

volumes:
  postgres-data:
    external: true
    name: komodo_postgres-data
  ferretdb-state:
    external: true
    name: komodo_ferretdb-state
