services:
  newt:
    image: fosrl/newt:1.9.0
    container_name: pangolin-newt
    restart: unless-stopped
    networks:
      - newt-periphery
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  newt-periphery:
    external: true
