services:
  omni:
    container_name: omni
    image: ghcr.io/siderolabs/omni:v1.4.6
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file: .env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ${ETCD_VOLUME_PATH}:/_out/etcd
      - ${ETCD_ENCRYPTION_KEY}:/omni.asc:ro
      - ${TLS_CERT}:/tls.crt:ro
      - ${TLS_KEY}:/tls.key:ro
    command: >
      --account-id=${OMNI_ACCOUNT_UUID}
      --name=${NAME}
      --cert=/tls.crt
      --key=/tls.key
      --machine-api-cert=/tls.crt
      --machine-api-key=/tls.key
      --private-key-source=file:///omni.asc
      --event-sink-port=${EVENT_SINK_PORT}
      --sqlite-storage-path=/_out/etcd/omni.db
      --bind-addr=${BIND_ADDR}
      --machine-api-bind-addr=${MACHINE_API_BIND_ADDR}
      --k8s-proxy-bind-addr=${K8S_PROXY_BIND_ADDR}
      --advertised-api-url=${ADVERTISED_API_URL}
      --advertised-kubernetes-proxy-url=${ADVERTISED_K8S_PROXY_URL}
      --siderolink-api-advertised-url=${SIDEROLINK_ADVERTISED_API_URL}
      --siderolink-wireguard-advertised-addr=${SIDEROLINK_WIREGUARD_ADVERTISED_ADDR}
      --enable-break-glass-configs
      --initial-users=${INITIAL_USER_EMAILS}
      ${AUTH}
