---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/minipcs
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-config
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/argocd-apps
  prune: true
  timeout: 5m0s
