apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuer.yaml
  - default-tls-cert.yaml
  - ipaddressPool.yaml
  - ceph-cluster.yaml
  - ceph/
  - monitoring-ns.yaml
  - seaweedfs-s3-secret.yaml
  - thanos-objstore-secret.yaml
