apiVersion: v1
kind: Secret
metadata:
    name: monitoring-basic-auth
    namespace: monitoring
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:kpT94Kn9/pC/Oh/n7DlANt/v/ogUcUc8eulBSKVA6/CsvJT3ExVf8IaYNyHshLusQqzHlJVe/R3ta22Nu6jjQIdS,iv:ZbwSEfZt/Rfc0XyqTy/oInw+eL9PNx6wiht6zMHTJOU=,tag:M2hAFGBvBWoSIXXjOfVnTw==,type:str]
    username: ENC[AES256_GCM,data:nNrTVs4=,iv:oCHaBV5jo+GbYKPlacaw0aBSwuwHTdjLSZsfT9NyQTU=,tag:3Gh4O2Eew4zm+aU2EzANLw==,type:str]
    password: ENC[AES256_GCM,data:YBTWfchoisT9XIkbQ60NETpE/nZqQ4cY/2LWoQvZJWWVkxnaYyl625AMfQ==,iv:VqcqPwnD30GHbvkqVG+tNCRm/VCAeArYdt/QzXX1PbY=,tag:kM6eoRjP6UvtwUyAr9JTRw==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvT3lybVZpSGh5c0VzbzRo
            RnVCZUlWcU9ta1V5RXl6dkFocHV3akIrQ2xFCmdKYk03MytFdnFNSlJNeXg3ekpi
            VWdyTWpTNm9FN3VpWUNGSFRsUzJnN0kKLS0tIDhjcUp1eDNHbmh5bFd4Ykg1YjE3
            L1dqTCsvcmR0NjBIc21GSGpVVXlSZnMKPIF6726d2q9P5MlhVntr9SagJnO5UJ5H
            6L3N3FFRNh2OSdnA2JWHvP4XGwEixgIO7cE3069LoLuuBr758AAMhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T07:55:10Z"
    mac: ENC[AES256_GCM,data:CA8A718FZFsor17Geg+j6Qhez9QlDh7o75mma/uesN3eQkUEGu3CZOeIivzqMpQyfcTvwHCwaVJlOW8MQSoxiwNdKUNm/kkcAXcXe72qvANS3YMwBzGifWfXUBU5+De0nCx26+X3zduP3mImpR/jYxpgj0GLO0zjrHG5nbXRxwY=,iv:4fUVMMD/CUDxqD4+Qvp/CGCtDKJUdzADo40ZYvCEnQQ=,tag:jPhyZEfpNaN+RPUCoJ6z0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
