apiVersion: v1
kind: Secret
metadata:
    name: monitoring-basic-auth
    namespace: monitoring
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:IBlcLCiuyVkyHvH3eZnhkUZVOGMMJXmDxqi96KjyuxmlNF4=,iv:Z8J1/e0Q3Uqyk0io/XxBE570CwDjMxYwXhUMZF7G5Ps=,tag:e4LFxvGZ5KYdFZiy9xrgLw==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QjlxWEtETzBXa3U4b2NY
            a1g5emYxWk96cy85ejR2dmpTYUVvc2UweGtVClRxMzRGNnkrTHNLQ1FzWUkrdnp2
            aW5UNzNMK3RmaXJiWENVcjdKTHVObFUKLS0tICtqenpaYzJxaFZHSmVYU084cU5X
            aE5yRzdoYWoyOUZGS245K21CVm40T28KKUbhxoLYMljz9E1Gx1xxz0CD15cA7jXV
            pCj1fVodYigUqTN5BbwR8jqGlBcXsPtw8oeOIM91LemNJYDUGz1G3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T07:40:17Z"
    mac: ENC[AES256_GCM,data:DaUSG1P2D6bZQQh2dHZm1Nw/+PKBNZ5Zs1uoWva45S3hp+CtAi/fRj5s+rW8aUlsxOE0DSAUQ3T2qPRwc2Shfy4+vP3o8R0NE03ijnwoJZObDCJXN5rKQADba9mvnL9O26Hp/RMv05KVhhHJsxPbqLpNSwLHZBTYsgvfwT9Y7qk=,iv:0JKTc3kt5xkR362r0DFjLrWYRF7kBCEl0iFoGXechIk=,tag:MNXJovimN5Oluqmh7LbTcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
