apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-secret
    namespace: monitoring
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:A88J2eT6BjbLgd/+R7Ki8iBwBGs=,iv:hdECu/u4bROvKFGPii3BAfz1HViZRhBDn1Os5fiKLDg=,tag:lp+vEQ7QC2Gbui9qIY8jbA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:EigFjqJqUH1+JvYAtZYVYi52CiHkDWU6nFhqthqI49qB5ppQFxj/kg==,iv:bQzNMbV5rjLJyN3fYaCS+9uNffOFwrtGwOZ8xszp5YE=,tag:lOOK5fq/cMyTR+YCrlF9Vw==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d3Z2dHd4NEh1RjNiMlNT
            dVpJZmtlY2xRMlJiVUJweGZFdWtuaktOT1UwCjN5dkpucHc1dHMvVGQ1U0lVYzJX
            bjIwVUlYeHY0UTNJai8zdThwbWNDMWcKLS0tIDBvNVM1NWdQQjUwd1AzM2hnL0dE
            QkhOYVhwNVFzK3ZWeFVRNS8wcE1LblkKZyoHZlXNcJLVcsfijK/hQ//5Gkccnb1c
            +3S4czV8TE+97MEpArzWQ/WP9JtnTqDhHrP2uPAfcjVIQn3eguW4vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T20:40:55Z"
    mac: ENC[AES256_GCM,data:N3uTViTaL6gmAuK0/kKSB2ke9bV7G867wdiBo8GsQWc5Vcb78wwxc/+cTjhKnwKdv3MQuard01yk03AejOVeGPXH9pN35SetfuZSE3WMXZw2ANgfk1C1bczNno/M2vMSt55kO5fC2oi2vjpzV/FVh6UHC4GGQzIkzz5IbaJA/ng=,iv:vGIhcDcvyQTE48LPdzyZXUqcnjNJXgz306eVT6xam+0=,tag:mLoN52B41g8SZpgozqZjJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
