apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: monitoring
type: Opaque
stringData:
    objstore.yml: ENC[AES256_GCM,data:sX/NVdCg3Vs2HWjQXsTa3eIbjLwLqxfauf0S9Vo3IxNyNs1QQwgUg93fndGORJNY1+UO/NIr+42wE+GA4Z82m2SDLPoowUD4g9mNm92PnMy7P3Ck2d1ZFnP5SA37yq8EKFYscN6hdnlLgPjbflEx4pyVMVppjaTxZ4VIrCkufqSwe1r29/X3lcDunPeib0oCJggBirgy+mpNCHGYoBmvjHbMYJH2cN+ZXTYvd/35t2jQ7udSu+A9ddzhlLM6XHf1,iv:NmD3mZujsSP9ceHLAdOa3rKgkLkrGicvLY3657gqVjE=,tag:/pQFIXU+BCjIk/VZuL/OGg==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMVdkak1nQ1l4RW9UVHYz
            RUVBV1EwSFp5dCt1R1NnbTJITW5lOUlodlFRCk0xNHJrbkUxUzdsQ09UM3RLT04z
            SDJ0NVoveXZ1b3plck5IcDF4azZqK2sKLS0tIFB1T21JOGpTQU1pbHJUL3U4bS9u
            YmNwTnpwUWdhK1ZkR2Y1Y0dSUFRZUlUKVFzLeusM+K7A3qThH0+YftYg6ZIa5wiN
            leijSEfelPgB8XbS/eJi5tjRXUwmhfXIcVlnN+MptqVzAd+9/xSHBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T20:41:02Z"
    mac: ENC[AES256_GCM,data:bA0MqWiPeyDO7WBxd43NrP30DB724igHxv3PXV/qLed+Wcltk99CSZWyHXvKz1JLWebHVQfCTKX767qFPXMa/p6dsv73WPe+Z3FHcv7jp+j28jM4xeng9Johc1EOeGM5xwD93zgZj0VYGIBxT1jSsrBVYWA8gTbTsWpkmsi396E=,iv:sBsllngZ8MbShIeq2bDKBieDzdfbgxT6uvmxsxdcxw4=,tag:T4hKALaFOZ8Zmy+s7Fm9yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
