services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - bookstack_db
    networks:
      - bookstack
      - traefik_proxy
    env_file: .sops.env
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://docs.sharmamohit.com
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack_config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.bookstack.entrypoints=http
      - traefik.http.routers.bookstack.rule=Host(`docs.sharmamohit.com`)
      - traefik.http.routers.bookstack-secure.entrypoints=https
      - traefik.http.routers.bookstack-secure.rule=Host(`docs.sharmamohit.com`)
      - traefik.http.routers.bookstack-secure.tls=true
      - traefik.http.routers.bookstack-secure.tls.certresolver=http
      - traefik.http.routers.bookstack-secure.service=bookstack
      - traefik.http.services.bookstack.loadbalancer.server.port=80
      - traefik.docker.network=traefik_proxy
      - traefik.http.services.bookstack.loadbalancer.server.scheme=http

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - bookstack
    env_file: .sops.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./sql_config:/config

networks:
  bookstack:
  traefik_proxy:
    external: true
