apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-webhook
    namespace: monitoring
type: Opaque
stringData:
    slack-webhook-url: ENC[AES256_GCM,data:XPqEth3Eih02Xl7OQsddAv/VNhGW8Jyub0vlf+FdN7Gdi0B92nNYjka48D1ALbDSwRV7MH9kQf1JhYEzDYjwfxNV6xmmDZwpkiZEmjWkLkac,iv:ayYbDDp7DhoP/CWsJGavri8mCRX5NIUNppWJrLRI3bo=,tag:DG4AI0uOz+Vf88G7fsXuaw==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQkliM3AyUzRsL0Vhckdq
            ODFOZEo1cU5BZkpDdEpuYzZhbEd1aC9SVjFFCmlWOVo0YkhYU29WcUNHa25GcjhM
            blpOYXU0UjhNNy9TNDJDeE1CQjU4OEUKLS0tIHVXMTltNjN2YmxoeUFYdGhBQi95
            VTQ4NVI1N3pHMHZ2Qm5qUGRzS0N4NkUKngXJ9d2qBX5DP7KoqnG79xV2A8FJK49B
            ltExuEqsTe9BSgOPKc/k/42cjHq2q9IBQFrTVTnWqbQj3C5+nQIsQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T05:39:56Z"
    mac: ENC[AES256_GCM,data:4xymonPVr46osVM8L9pnfp4uhyKZl1iZoPypILSXC5kNwp1UjKKX0TE8u+FFKAiNz2ag0l9U9kStCklKXixVeV4rJNENx/rfs0VsgK51hDl/4EWX1qYOo0sqy85MkMLUXxQLEmu3W0qeInCd+VyEgtPbIdSsOCQMYwNtkKoRW6s=,iv:I6JOm5CjZOciOj86DTx9MDFGyhZxsxJ31PGsXztuzZQ=,tag:oBzM3G1WGivKrj1VAypcfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
