apiVersion: v1
kind: Secret
metadata:
    name: newt-credentials
    namespace: pangolin
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:/ROoe9tb1kxN4ZCzG/sgGo6DNlCujVhhs1PI6OX9+CvMFHP+CQQ=,iv:DLh1xCaH3w8tRca5R1+pJq2KLAjJ5/9iX9vvoruNe60=,tag:mIIBnlqyWjHQipnDFmkTeg==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:SQP6AMSGdSI/5qgf18R+,iv:U9jFHYS9q5yQIjsTSCmS8GMHqZL1Ay6FJ4Xfwu4w83c=,tag:fWdzPsU2xxpNe7FggmbHJg==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:I/R/qaPEKBgWq3I716oljvMOYiYwkRLVWYkipHbfgoRTjQE203JaeNqHWAwV9Gni,iv:Z6e77Kpozi5s62JMWIh2laX+6t6gQe98sWnfU+dnV54=,tag:XqG4dF7g0Eh15d6L3EIgtA==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dkl2VHBaeWJUaVdkR0s5
            eEQvS2lGYW5nTlRDTTk0RVJzMjJDSnBla3lzCjJyTWs2a001UDA5ZzVQRlh1cm9C
            dEJYc2ZjeDlhM0htQW42ejVxQTJXSm8KLS0tIE14dzBVUDBoNkoxN2ZlYzRWcjQ5
            alNUbWNtZ2xXZSs3SW1TaTNMTmhvRHMKXhpABGdsV6KIzUYScpVsKvxqAk87FCWm
            fuHV2Ph8xav59SI5unQxcCXiqMk0ZuSDmff31serO0kxb9DKJwDhtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T06:12:33Z"
    mac: ENC[AES256_GCM,data:QtiFnZJfoB6vMSsr1IG9keSs57IVVIdsiQs8DjrO/N5rxbGBdBXlZwg5zF/pLdMkTJOMfZbx7WdC++dIaV4SDaR4qOlJq3MX7z2wVWHo5+lT0dn0dJWMM22IaKyYo8aQeMEIBcdum1re4hQajmIZKWq74jdYFXmHRnB50VfgSv4=,iv:D2oR7+G5UyBWwAStE0oo6Me/CMHTsUAqlaPbCMItWsY=,tag:xxE92Wfyv1FBK4MKnC5SOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
