[[builder]]
name = "server04-builder"
description = "Docker build server on server04"
tags = ["system"]
[builder.config]
type = "Server"
params.server = "server04"

[[build]]
name = "periphery-custom"
description = "Custom Komodo Periphery with SOPS + age"
tags = ["system", "periphery"]
[build.config]
builder = "server04-builder"
repo = "mohitsharma44/homeops"
branch = "main"
build_path = "docker/periphery"
dockerfile_path = "Dockerfile"
image_registry.type = "Standard"
image_registry.params.domain = "docker.io"
image_registry.params.account = "mohitsharma44"
image_name = "mohitsharma44/komodo-periphery-sops"
