services:
  newt:
    container_name: newt
    image: fosrl/newt:1.7.0
    restart: unless-stopped
    env_file: .env
    environment:
      PANGOLIN_ENDPOINT: https://pangolin.proxy.sharmamohit.com
    security_opt:
      - "no-new-privileges:true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
